DefaultContentLanguage = "en"
#DefaultContentLanguageInSubdir = true
copyright = "Everything is mine"
baseURL = "http://snakeword.vit.ooo/"
#baseURL = "https://goshva.github.io/snakeword/"
languageCode = "en-us"
title = "My snakeword game"
theme = ["snakeword"]
publishDir ="docs"
[Languages]
[Languages.en]
  Languagename =  "English"

  title = "Snakeword"
  weight = 1
  author = "Sha. Egor"
  Description = "Take a word by side by side letters"
  keywords = "Tesla's Awesome Hugo Site"
  fbAppid = "Tesla's Awesome Hugo Site"
  Fullurl = "Tesla's Awesome Hugo Site"
  Points = "0"
  MyRecord = "0"
  Game_Mode = "game mode"
  Random = "Random"
  Settings = "Set"
  Save = "Save"
  Language = "Language"


[Languages.ru]
  Languagename =  "Русский"
  title = "Змееслов"
  weight = 2
  author = "Егор Ша."
  Description = "Игра собери слово"
  keywords = "Tesla's Awesome Hugo Site"
  fbAppid = "Tesla's Awesome Hugo Site"
  Fullurl = "Tesla's Awesome Hugo Site"
  Points = "0"
  MyRecord = "0"
  Game_Mode = "Вид игры"
  Random = "Хаос"
  Settings = "Набор"
  Save = "Сохранить"
  Language = "Язык"

[Languages.de]
  Languagename =  "Немецкий"
  title = "Змееслов"
  weight = 2
  author = "Егор Ша."
  Description = "Nehmen Sie ein Wort nebeneinander Buchstaben"
  keywords = "Tesla's Awesome Hugo Site"
  fbAppid = "Tesla's Awesome Hugo Site"
  Fullurl = "Tesla's Awesome Hugo Site"
  Points = "0"
  MyRecord = "0"
  Game_Mode = "Вид игры"
  Random = "Chaos"
  Settings = "Bausatz"
  Save = "Speichern"
  Language = " Sprache"

[Languages.fr]
  Languagename =  "French"

  title = "Snakeword"
  weight = 1
  author = "Sha. Egor"
  Description = "Prendre un mot à côté des lettres côte à côte"
  keywords = "Tesla's Awesome Hugo Site"
  fbAppid = "Tesla's Awesome Hugo Site"
  Fullurl = "Tesla's Awesome Hugo Site"
  Points = "0"
  MyRecord = "0"
  Game_Mode = "game mode"
  Random = "Le chaos"
  Settings = "Set"
  Save = "Sauver"
  Language = "Langue"

[Languages.la]  
  Languagename =  "Latin"

  title = "Anguis"
  weight = 1
  author = "Sha. Egor"
  Description = "Accipe verbum iuxta litteras iuxta"
  keywords = "Tesla's Awesome Hugo Site"
  fbAppid = "Tesla's Awesome Hugo Site"
  Fullurl = "Tesla's Awesome Hugo Site"
  Points = "0"
  MyRecord = "0"
  Game_Mode = "game mode"
  Random = "Chaos"
  Settings = "Set"
  Save = "salvare"
  Languege = "Lingua"

[Languages.ar]
  Languagename =  "Arabian"

  title = "Snakeword"
  weight = 1
  author = "Sha. Egor"
  Description = "خذ كلمة جنبًا إلى جنب"
  keywords = "Tesla's Awesome Hugo Site"
  fbAppid = "Tesla's Awesome Hugo Site"
  Fullurl = "Tesla's Awesome Hugo Site"
  Points = "0"
  MyRecord = "0"
  Game_Mode = "game mode"
  Random = "فوضى"
  Settings = "Set"
  Save = "يحفظ"
  Language = "لغة"
[taxonomies]
  category = "categories"
  tag = "tags"

